apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    
    global:
      scrape_interval: 4s

    scrape_configs:
      - job_name: 'node-app'
        metrics_path: '/metrics'
        scheme: 'https'
        static_configs:
          - targets: ['splitwise-242x.onrender.com']

