apiVersion: v1
kind: Service
metadata:
  name: splitwise
spec:
  selector:
    app: splitwise
  ports:
    - protocol: TCP
      port: 7070      # Service port
      targetPort: 7070  # Container port
  type: ClusterIP

