apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'split-wise'
        static_configs:
          - targets: ['splitwise-242x.onrender.com']
        scheme: https
        metrics_path: '/metrics'